### PR TITLE
pyQuil: qvm and quilc helper functions

### PR DESCRIPTION
**Pull request by obliviateandsurrender**
`activate_qvm_quilc`, and `deactivate_qvm_quilc` are the utility functions that will allow automatic activation and deactivation of qvm and quilc server required for pyQuil.

### CODE REVIEW

**Review by rmlarose — APPROVED** [review]
LGTM. There's some minor doc-string formatting to keep consistency, but I can take care of this. Thanks for this!

**Comment by rmlarose** [comment]
Additionally, it would be nice if stopping the QVM and/or QUILC didn't require input arguments, if this is even possible.

**Comment by obliviateandsurrender** [comment]
I'll check once and update you regarding this.

**Comment by obliviateandsurrender** [comment]
> I'll check once and update you regarding this.

Also, in addition, I'll update the #TODOs in the code with a brief description.

**Pull request merged**
